[2024-07-16T10:28:27.163+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T10:28:27.180+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_id_3.check_if_table_exists manual__2024-07-16T10:28:24.601752+00:00 [queued]>
[2024-07-16T10:28:27.184+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_id_3.check_if_table_exists manual__2024-07-16T10:28:24.601752+00:00 [queued]>
[2024-07-16T10:28:27.184+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-16T10:28:27.191+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_if_table_exists> on 2024-07-16 10:28:24.601752+00:00
[2024-07-16T10:28:27.194+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=464) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T10:28:27.195+0000] {standard_task_runner.py:63} INFO - Started process 466 to run task
[2024-07-16T10:28:27.195+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_id_3', 'check_if_table_exists', 'manual__2024-07-16T10:28:24.601752+00:00', '--job-id', '1540', '--raw', '--subdir', 'DAGS_FOLDER/dag_id_3.py', '--cfg-path', '/tmp/tmpfdk8w6po']
[2024-07-16T10:28:27.197+0000] {standard_task_runner.py:91} INFO - Job 1540: Subtask check_if_table_exists
[2024-07-16T10:28:27.233+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_id_3.check_if_table_exists manual__2024-07-16T10:28:24.601752+00:00 [running]> on host a1689f3248db
[2024-07-16T10:28:27.300+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_id_3' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T10:28:24.601752+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T10:28:24.601752+00:00'
[2024-07-16T10:28:27.301+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T10:28:27.302+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-07-16T10:28:27.302+0000] {python.py:237} INFO - Done. Returned value was: insert_new_row
[2024-07-16T10:28:27.302+0000] {branch.py:36} INFO - Branch into insert_new_row
[2024-07-16T10:28:27.303+0000] {skipmixin.py:178} INFO - Following branch insert_new_row
[2024-07-16T10:28:27.320+0000] {skipmixin.py:246} INFO - Skipping tasks [('create_table', -1)]
[2024-07-16T10:28:27.343+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T10:28:27.364+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_id_3, task_id=check_if_table_exists, run_id=manual__2024-07-16T10:28:24.601752+00:00, execution_date=20240716T102824, start_date=20240716T102827, end_date=20240716T102827
[2024-07-16T10:28:27.375+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-16T10:28:27.399+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T10:28:27.400+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
