[2024-07-22T13:41:28.898+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T13:41:29.114+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T13:41:26.017671+00:00 [queued]>
[2024-07-22T13:41:29.128+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T13:41:26.017671+00:00 [queued]>
[2024-07-22T13:41:29.138+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T13:41:29.186+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_count_number_of_accidents> on 2024-07-22 13:41:26.017671+00:00
[2024-07-22T13:41:29.212+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=191) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T13:41:29.229+0000] {standard_task_runner.py:63} INFO - Started process 204 to run task
[2024-07-22T13:41:29.224+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'count_accidents', 'spark_count_number_of_accidents', 'manual__2024-07-22T13:41:26.017671+00:00', '--job-id', '1817', '--raw', '--subdir', 'DAGS_FOLDER/count_accidents.py', '--cfg-path', '/tmp/tmp0z_tt88w']
[2024-07-22T13:41:29.246+0000] {standard_task_runner.py:91} INFO - Job 1817: Subtask spark_count_number_of_accidents
[2024-07-22T13:41:29.541+0000] {task_command.py:426} INFO - Running <TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T13:41:26.017671+00:00 [running]> on host d4440bb16398
[2024-07-22T13:41:29.842+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_accidents' AIRFLOW_CTX_TASK_ID='spark_count_number_of_accidents' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T13:41:26.017671+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T13:41:26.017671+00:00'
[2024-07-22T13:41:29.851+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T13:41:29.922+0000] {base.py:84} INFO - Using connection ID 'spark' for task execution.
[2024-07-22T13:41:29.934+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master localhost:7077 --name arrow-spark --deploy-mode client /opt/airflow/spark/count_rows.py
[2024-07-22T13:41:30.269+0000] {spark_submit.py:571} INFO - /home/airflow/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-07-22T13:41:30.284+0000] {spark_submit.py:571} INFO - /home/airflow/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-17-openjdk-amd64/bin/java: No such file or directory
[2024-07-22T13:41:30.287+0000] {spark_submit.py:571} INFO - /home/airflow/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2024-07-22T13:41:30.292+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T13:41:30.340+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master localhost:7077 --name arrow-spark --deploy-mode client /opt/airflow/spark/count_rows.py. Error code is: 1.
[2024-07-22T13:41:30.368+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=count_accidents, task_id=spark_count_number_of_accidents, run_id=manual__2024-07-22T13:41:26.017671+00:00, execution_date=20240722T134126, start_date=20240722T134129, end_date=20240722T134130
[2024-07-22T13:41:30.452+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1817 for task spark_count_number_of_accidents (Cannot execute: spark-submit --master localhost:7077 --name arrow-spark --deploy-mode client /opt/airflow/spark/count_rows.py. Error code is: 1.; 204)
[2024-07-22T13:41:30.481+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-22T13:41:30.600+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T13:41:30.609+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
