[2024-07-18T08:01:05.128+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-18T08:01:05.143+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_id_3.check_if_table_exists manual__2024-07-18T08:01:02.945334+00:00 [queued]>
[2024-07-18T08:01:05.147+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_id_3.check_if_table_exists manual__2024-07-18T08:01:02.945334+00:00 [queued]>
[2024-07-18T08:01:05.147+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-18T08:01:05.153+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_if_table_exists> on 2024-07-18 08:01:02.945334+00:00
[2024-07-18T08:01:05.156+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=143) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-18T08:01:05.157+0000] {standard_task_runner.py:63} INFO - Started process 145 to run task
[2024-07-18T08:01:05.158+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_id_3', 'check_if_table_exists', 'manual__2024-07-18T08:01:02.945334+00:00', '--job-id', '1563', '--raw', '--subdir', 'DAGS_FOLDER/dag_id_3.py', '--cfg-path', '/tmp/tmps9lkwr39']
[2024-07-18T08:01:05.159+0000] {standard_task_runner.py:91} INFO - Job 1563: Subtask check_if_table_exists
[2024-07-18T08:01:05.206+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_id_3.check_if_table_exists manual__2024-07-18T08:01:02.945334+00:00 [running]> on host 4d13026947d2
[2024-07-18T08:01:05.273+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_id_3' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T08:01:02.945334+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T08:01:02.945334+00:00'
[2024-07-18T08:01:05.274+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-18T08:01:05.275+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-07-18T08:01:05.275+0000] {python.py:237} INFO - Done. Returned value was: create_table
[2024-07-18T08:01:05.275+0000] {branch.py:36} INFO - Branch into create_table
[2024-07-18T08:01:05.275+0000] {skipmixin.py:178} INFO - Following branch create_table
[2024-07-18T08:01:05.292+0000] {skipmixin.py:246} INFO - Skipping tasks []
[2024-07-18T08:01:05.303+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-18T08:01:05.321+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_id_3, task_id=check_if_table_exists, run_id=manual__2024-07-18T08:01:02.945334+00:00, execution_date=20240718T080102, start_date=20240718T080105, end_date=20240718T080105
[2024-07-18T08:01:05.337+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-18T08:01:05.360+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T08:01:05.361+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
