[2024-07-22T13:54:39.490+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T13:54:39.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T13:54:38.381438+00:00 [queued]>
[2024-07-22T13:54:39.511+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T13:54:38.381438+00:00 [queued]>
[2024-07-22T13:54:39.511+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T13:54:39.517+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_count_number_of_accidents> on 2024-07-22 13:54:38.381438+00:00
[2024-07-22T13:54:39.521+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=538) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T13:54:39.522+0000] {standard_task_runner.py:63} INFO - Started process 540 to run task
[2024-07-22T13:54:39.524+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'count_accidents', 'spark_count_number_of_accidents', 'manual__2024-07-22T13:54:38.381438+00:00', '--job-id', '1831', '--raw', '--subdir', 'DAGS_FOLDER/count_accidents.py', '--cfg-path', '/tmp/tmp1ace1i6e']
[2024-07-22T13:54:39.526+0000] {standard_task_runner.py:91} INFO - Job 1831: Subtask spark_count_number_of_accidents
[2024-07-22T13:54:39.585+0000] {task_command.py:426} INFO - Running <TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T13:54:38.381438+00:00 [running]> on host d4440bb16398
[2024-07-22T13:54:39.660+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_accidents' AIRFLOW_CTX_TASK_ID='spark_count_number_of_accidents' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T13:54:38.381438+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T13:54:38.381438+00:00'
[2024-07-22T13:54:39.663+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T13:54:39.675+0000] {base.py:84} INFO - Using connection ID 'spark' for task execution.
[2024-07-22T13:54:39.677+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark2-submit --master spark://localhost:7077 --name arrow-spark --deploy-mode client /opt/airflow/spark/count_rows.py
[2024-07-22T13:54:39.678+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T13:54:39.678+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 481, in submit
    self._submit_sp = subprocess.Popen(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark2-submit'
[2024-07-22T13:54:39.688+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=count_accidents, task_id=spark_count_number_of_accidents, run_id=manual__2024-07-22T13:54:38.381438+00:00, execution_date=20240722T135438, start_date=20240722T135439, end_date=20240722T135439
[2024-07-22T13:54:39.696+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1831 for task spark_count_number_of_accidents ([Errno 13] Permission denied: 'spark2-submit'; 540)
[2024-07-22T13:54:39.705+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-22T13:54:39.720+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T13:54:39.721+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
