[2024-07-19T11:44:46.146+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T11:44:46.162+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_id_3.check_if_table_exists manual__2024-07-19T11:44:43.189387+00:00 [queued]>
[2024-07-19T11:44:46.166+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_id_3.check_if_table_exists manual__2024-07-19T11:44:43.189387+00:00 [queued]>
[2024-07-19T11:44:46.166+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-19T11:44:46.173+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_if_table_exists> on 2024-07-19 11:44:43.189387+00:00
[2024-07-19T11:44:46.176+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=641) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T11:44:46.177+0000] {standard_task_runner.py:63} INFO - Started process 643 to run task
[2024-07-19T11:44:46.178+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_id_3', 'check_if_table_exists', 'manual__2024-07-19T11:44:43.189387+00:00', '--job-id', '1600', '--raw', '--subdir', 'DAGS_FOLDER/dag_id_3.py', '--cfg-path', '/tmp/tmphk_72l28']
[2024-07-19T11:44:46.179+0000] {standard_task_runner.py:91} INFO - Job 1600: Subtask check_if_table_exists
[2024-07-19T11:44:46.220+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_id_3.check_if_table_exists manual__2024-07-19T11:44:43.189387+00:00 [running]> on host b6c6b8dd133d
[2024-07-19T11:44:46.298+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_id_3' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T11:44:43.189387+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T11:44:43.189387+00:00'
[2024-07-19T11:44:46.299+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T11:44:46.300+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-07-19T11:44:46.301+0000] {python.py:237} INFO - Done. Returned value was: insert_new_row
[2024-07-19T11:44:46.301+0000] {branch.py:36} INFO - Branch into insert_new_row
[2024-07-19T11:44:46.301+0000] {skipmixin.py:178} INFO - Following branch insert_new_row
[2024-07-19T11:44:46.323+0000] {skipmixin.py:246} INFO - Skipping tasks [('create_table', -1)]
[2024-07-19T11:44:46.347+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T11:44:46.365+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_id_3, task_id=check_if_table_exists, run_id=manual__2024-07-19T11:44:43.189387+00:00, execution_date=20240719T114443, start_date=20240719T114446, end_date=20240719T114446
[2024-07-19T11:44:46.397+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-19T11:44:46.424+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T11:44:46.425+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
