[2024-07-15T13:40:20.498+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:40:20.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:40:20.501+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:40:20.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:40:20.514+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:40:20.513+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:40:20.514+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:40:20.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.025 seconds
[2024-07-15T13:40:50.692+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:40:50.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:40:50.694+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:40:50.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:40:50.709+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:40:50.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:40:50.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:40:50.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.025 seconds
[2024-07-15T13:41:21.295+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:41:21.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:41:21.298+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:41:21.298+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:41:21.311+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:41:21.310+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:41:21.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:41:21.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.026 seconds
[2024-07-15T13:41:51.349+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:41:51.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:41:51.350+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:41:51.350+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:41:51.362+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:41:51.360+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:41:51.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:41:51.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.024 seconds
[2024-07-15T13:42:21.471+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:42:21.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:42:21.477+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:42:21.477+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:42:21.492+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:42:21.491+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:42:21.492+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:42:21.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.031 seconds
[2024-07-15T13:42:51.833+0000] {processor.py:161} INFO - Started process (PID=353) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:42:51.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:42:51.835+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:42:51.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:42:51.845+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:42:51.844+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:42:51.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:42:51.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.020 seconds
[2024-07-15T13:43:21.934+0000] {processor.py:161} INFO - Started process (PID=417) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:43:21.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:43:21.936+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:43:21.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:43:21.959+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:43:21.957+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:43:21.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:43:21.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.035 seconds
[2024-07-15T13:43:52.000+0000] {processor.py:161} INFO - Started process (PID=480) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:43:52.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:43:52.003+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:43:52.003+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:43:52.020+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:43:52.019+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:43:52.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:43:52.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.032 seconds
[2024-07-15T13:44:22.405+0000] {processor.py:161} INFO - Started process (PID=545) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:44:22.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:44:22.407+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:44:22.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:44:22.418+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:44:22.417+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:44:22.419+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:44:22.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.022 seconds
[2024-07-15T13:45:45.828+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:45:45.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:45:45.833+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:45:45.833+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:45:45.874+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:45:45.870+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:45:45.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:45:45.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.077 seconds
[2024-07-15T13:46:16.695+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:46:16.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:46:16.697+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:46:16.697+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:46:16.709+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:46:16.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:46:16.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:46:16.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.023 seconds
[2024-07-15T13:46:47.458+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:46:47.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:46:47.460+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:46:47.460+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:46:47.471+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:46:47.470+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:46:47.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:46:47.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.022 seconds
[2024-07-15T13:47:17.577+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:47:17.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:47:17.581+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:47:17.580+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:47:17.593+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:47:17.592+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:47:17.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:47:17.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.026 seconds
[2024-07-15T13:47:48.012+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:47:48.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:47:48.014+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:47:48.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:47:48.026+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:47:48.025+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:47:48.026+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:47:48.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.022 seconds
[2024-07-15T13:48:18.325+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:48:18.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:48:18.327+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:48:18.327+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:48:18.341+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:48:18.339+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:48:18.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:48:18.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.025 seconds
[2024-07-15T13:48:48.644+0000] {processor.py:161} INFO - Started process (PID=416) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:48:48.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:48:48.647+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:48:48.647+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:48:48.658+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:48:48.657+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:48:48.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:48:48.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.024 seconds
[2024-07-15T13:49:46.162+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:49:46.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:49:46.164+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:49:46.164+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:49:46.174+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:49:46.173+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:49:46.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:49:46.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.020 seconds
[2024-07-15T13:50:16.963+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:50:16.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:50:16.965+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:50:16.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:50:16.976+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:50:16.975+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:50:16.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:50:16.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.021 seconds
[2024-07-15T13:50:47.133+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:50:47.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:50:47.135+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:50:47.135+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:50:47.146+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:50:47.145+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:50:47.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:50:47.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.020 seconds
[2024-07-15T13:51:17.425+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:51:17.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:51:17.427+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:51:17.427+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:51:17.438+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:51:17.437+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:51:17.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:51:17.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.022 seconds
[2024-07-15T13:51:47.516+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:51:47.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:51:47.518+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:51:47.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:51:47.528+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:51:47.527+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:51:47.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:51:47.533+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.020 seconds
[2024-07-15T13:52:52.090+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:52:52.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:52:52.092+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:52:52.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:52:52.104+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:52:52.102+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:52:52.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:52:52.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.023 seconds
[2024-07-15T13:53:22.810+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:53:22.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:53:22.814+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:53:22.813+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:53:22.826+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:53:22.825+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:53:22.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:53:22.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.038 seconds
[2024-07-15T13:53:53.537+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:53:53.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:53:53.538+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:53:53.538+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:53:53.548+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:53:53.547+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:53:53.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:53:53.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.021 seconds
[2024-07-15T13:54:23.781+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:54:23.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:54:23.784+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:54:23.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:54:23.798+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:54:23.797+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:54:23.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:54:23.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.025 seconds
[2024-07-15T13:54:53.930+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:54:53.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:54:53.932+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:54:53.932+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:54:53.944+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:54:53.943+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:54:53.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:54:53.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.023 seconds
[2024-07-15T13:55:24.174+0000] {processor.py:161} INFO - Started process (PID=353) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:55:24.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:55:24.177+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:55:24.176+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:55:24.190+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:55:24.189+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:55:24.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:55:24.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.025 seconds
[2024-07-15T13:55:55.227+0000] {processor.py:161} INFO - Started process (PID=418) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:55:55.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:55:55.229+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:55:55.229+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:55:55.240+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:55:55.239+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:55:55.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:55:55.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.021 seconds
[2024-07-15T13:56:25.438+0000] {processor.py:161} INFO - Started process (PID=482) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:56:25.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:56:25.440+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:56:25.440+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:56:25.454+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:56:25.453+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:56:25.455+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:56:25.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.027 seconds
[2024-07-15T13:56:55.666+0000] {processor.py:161} INFO - Started process (PID=546) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:56:55.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:56:55.667+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:56:55.667+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:56:55.680+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:56:55.677+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:56:55.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:56:55.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.026 seconds
[2024-07-15T13:57:25.853+0000] {processor.py:161} INFO - Started process (PID=610) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:57:25.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:57:25.855+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:57:25.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:57:25.868+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:57:25.866+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:57:25.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:57:25.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.027 seconds
[2024-07-15T13:57:56.046+0000] {processor.py:161} INFO - Started process (PID=674) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:57:56.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:57:56.048+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:57:56.048+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:57:56.059+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:57:56.058+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:57:56.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:57:56.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.021 seconds
[2024-07-15T13:58:26.140+0000] {processor.py:161} INFO - Started process (PID=738) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:58:26.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:58:26.142+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:58:26.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:58:26.153+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:58:26.152+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:58:26.154+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:58:26.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.021 seconds
[2024-07-15T13:58:56.195+0000] {processor.py:161} INFO - Started process (PID=801) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:58:56.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:58:56.198+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:58:56.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:58:56.212+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:58:56.210+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:58:56.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:58:56.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.029 seconds
[2024-07-15T13:59:26.515+0000] {processor.py:161} INFO - Started process (PID=866) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:59:26.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:59:26.518+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:59:26.517+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:59:26.530+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:59:26.529+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:59:26.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:59:26.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.025 seconds
[2024-07-15T13:59:56.725+0000] {processor.py:161} INFO - Started process (PID=930) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:59:56.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T13:59:56.727+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:59:56.727+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:59:56.738+0000] {logging_mixin.py:188} INFO - [2024-07-15T13:59:56.737+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T13:59:56.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T13:59:56.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.022 seconds
[2024-07-15T14:00:26.894+0000] {processor.py:161} INFO - Started process (PID=994) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:00:26.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T14:00:26.896+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:00:26.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:00:26.906+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:00:26.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T14:00:26.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:00:26.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.020 seconds
[2024-07-15T14:00:56.946+0000] {processor.py:161} INFO - Started process (PID=1057) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:00:56.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T14:00:56.949+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:00:56.948+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:00:56.963+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:00:56.962+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T14:00:56.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:00:56.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.029 seconds
[2024-07-15T14:01:27.064+0000] {processor.py:161} INFO - Started process (PID=1121) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:01:27.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T14:01:27.067+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:01:27.066+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:01:27.083+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:01:27.082+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T14:01:27.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:01:27.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.034 seconds
[2024-07-15T14:01:57.286+0000] {processor.py:161} INFO - Started process (PID=1186) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:01:57.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T14:01:57.288+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:01:57.287+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:01:57.298+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:01:57.297+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T14:01:57.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:01:57.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.021 seconds
[2024-07-15T14:02:27.415+0000] {processor.py:161} INFO - Started process (PID=1250) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:02:27.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T14:02:27.417+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:02:27.417+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:02:27.428+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:02:27.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T14:02:27.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:02:27.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.022 seconds
[2024-07-15T14:02:57.558+0000] {processor.py:161} INFO - Started process (PID=1313) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:02:57.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T14:02:57.560+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:02:57.560+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:02:57.573+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:02:57.572+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T14:02:57.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:02:57.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.027 seconds
[2024-07-15T14:03:27.676+0000] {processor.py:161} INFO - Started process (PID=1377) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:03:27.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T14:03:27.679+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:03:27.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:03:27.694+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:03:27.692+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T14:03:27.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:03:27.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.030 seconds
[2024-07-15T14:03:57.999+0000] {processor.py:161} INFO - Started process (PID=1442) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:03:58.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T14:03:58.001+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:03:58.001+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:03:58.014+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:03:58.013+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T14:03:58.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:03:58.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.025 seconds
[2024-07-15T14:04:28.080+0000] {processor.py:161} INFO - Started process (PID=1505) to work on /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:04:28.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-07-15T14:04:28.083+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:04:28.083+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:04:28.095+0000] {logging_mixin.py:188} INFO - [2024-07-15T14:04:28.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 22, in <module>
    path = Variable.get("path")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable path does not exist'
[2024-07-15T14:04:28.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-07-15T14:04:28.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.026 seconds
